settings:
  title: 'Status Page'
  url: 'https://status-page.dragonsecurity.workers.dev/' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:   
  - id: www-taiosolve-xyz
    name: Taiosolve
    url: 'https://taiosolve.xyz/'
    method: GET
    expectStatus: 200

  - id: linaccess-za-net
    name: Linaccess
    url: 'https://linaccess.za.net'
    method: GET
    expectStatus: 200
    
  - id: ctrltilde-com
    name: CTRL Tilde
    url: 'https://CtrlTilde.com'
    method: GET
    expectStatus: 200
    
  - id: automanage-co-za
    name: Automanage
    url: 'https://automanage.co.za'
    method: GET
    expectStatus: 200
  
  - id: cosmo-tech
    name: Cleanpay
    url: 'https://cosmo.tech'
    method: GET
    expectStatus: 200

  - id: eu-nuvalaw
    name: 'Nuvalaw Europe'
    url: 'https://platform.nuvalaw.com'
    method: GET
    expectStatus: 200

  - id: usa-nuvalaw
    name: 'Nuvalaw USA'
    url: 'https://usa.nuvalaw.com'
    method: GET
    expectStatus: 200

  
